spring:
  datasource:
#driver-class-name: com.mysql.jc.jdbc.Driver
    url: jdbc:mysql://localhost/demo?bookshop=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8888
